#!/bin/bash

root_dir=$(realpath "$(dirname "$0")"/..)
. "$root_dir/dev-tools/base"

# Nice! 🌈
BLUE='\033[0;34m'
NC='\033[0m' # No Color

set -euo pipefail

cd "$root_dir"

for i in "${modules[@]}"; do
  echo -e "${BLUE}Checking module: $i${NC}"
  npx npm-check-updates --cwd "$i" "$@"
done
