#!/bin/sh

# A simple script for reinstalling UI deps.

root_dir=`realpath "$(dirname "$0")"/..`
. "$root_dir/dev-tools/base"

flushModuleNpm() {
  echo "${BLUE}Flushing NPMs for module: $1${NC}"
  cd "$root_dir/$1"
  
  rm -rf node_modules package-lock.json
  npm install --loglevel=warn --progress
}

set -euo pipefail

for i in "${modules[@]}"; do flushModuleNpm $i;  done
